services:
  - type: web
    name: lolroster-api
    env: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: lolroster-db
          property: connectionString

databases:
  - name: lolroster-db
    databaseName: lolroster
    plan: free
